baseURL = "http://2027.computational-humanities-research/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Computational Humanities Research 2027"
theme = "chr"
publishDir = "docs"

[params]
  customCSS = ["css/custom.css"]
  short = "CHR2027"

[menu]

  # [[menu.main]]
    # identifier = "cfp"
    # name = "CfP"
    # url = "/cfp"
    # weight = -2000

   # [[menu.main]]
     # identifier = "news"
     # name = "News"
     # url = "/news"
     # weight = -1850

   # [[menu.main]]
     # identifier = "venue"
     # name = "Venue"
     # url = "/venue"
     # weight = -1750

  # [[menu.main]]
     # identifier = "programme"
     # name = "Programme"
     # url = "/programme"
     # weight = -1500
    
  [[menu.main]]
      identifier = "about"
      name = "About"
      url = "/about"
      weight = -1000


[markup.goldmark.renderer]
unsafe = true
